### PR TITLE
Create base abilities menu

### LINKED ISSUE #62: Combat UI: Abilities Menu

### PR DESCRIPTION
**Pull request by eli-lam**
image

Implemented in this PR:
- Created AbilityDescription Scriptable Object to store ability information (name, description, and possibly cost)
- Imported basic placeholder assets for the ability menu
- When the mouse is hovering over an ability circle, an animation will start playing and the description panel will show
- Fully functional prefab created

Only implemented on the Combat UI Draft scene in my sandbox for now so that it doesn't interfere with current PRs.

Resolves #62

### CODE REVIEW

**Review by jmcduff — APPROVED** [review]
I haven't tested on Unity, but code-wise this looks good to me dOwOb

**Comment by jmcduff** [comment]
I would wait for someone else to test this before merging =w=

**Review by danielwiktorczyk — APPROVED** [review]
Haven't tested in Unity yet, but from the screen shot you sent, and from the code below, it's a great start!! Thanks for making a bite sized PR, and using Interactive Rebase effectively 👏

I don't see any conflicts with the current code, so Hit that green button when you're ready!

**Review by armandorusso — APPROVED** [review]
UI looks really good and the code looks good too! Tested in Unity as well and it works great!

**Pull request merged**
