### PR TITLE
Pimpkin, Ghost and Sield Prefabs

### PR DESCRIPTION
**Pull request by George540**

### CODE REVIEW

**Review by danielwiktorczyk — COMMENTED** [review]
Code wise, looks good! Only file additions, shouldn't conflict with anything

**Review by armandorusso — APPROVED** [review]
Love the animation and the prefab! Exactly how I pictured it!

**Review by danielwiktorczyk — APPROVED** [review]
Cool! The friendly NPC ghosts could do without those veins tho , looks disturbing  😱

**Comment by eli-lam** [comment]
Can't really check in unity because of the broken camera, but looks good from the screenshots! Maybe make the ghost a little friendlier?

**Review by eli-lam — APPROVED** [review]

**Pull request merged**
