### PR TITLE
Refine Map Details

### PR DESCRIPTION
**Pull request by armandorusso**
- Made the mountains look more like mountains
- Refined pathway, made it more defined and clearer to see
- Removed a lot of the bumps along the pathway and camera clipping
- Smoothed out the terrain and pathway in general
- Made trees look bigger
- Adjusted Cemetery Area

### CODE REVIEW

**Review by George540 — CHANGES_REQUESTED** [review]
Suggestions:

- Since new textures have been added, adjust painting for terrain properly
- Add more grass density (can apply for rocks, mushrooms and trees). Don't be afraid to add a bit more
- I adjusted the Rock texture (last layer found in the paint texture tab) so you can use that for steep hills as well, for finishing touches

**Review by danielwiktorczyk — APPROVED** [review]
Went through a lot of this with you remotely, changes look great! Nice work 😎

**Review by George540 — CHANGES_REQUESTED** [review]
Looks very good! Just put less green grass on the village. If we stick to the burning village, we should have less grass there since it's getting burned lol

**Review by George540 — APPROVED** [review]
Looks great! Love the island

**Pull request merged**
