### PR TITLE
Add Sield and Skeletoodle models

### PR DESCRIPTION
**Pull request by George540**
Contains the following entities:
- FBX Models
- Armatures
- Animation Actions
- Textures with corresponding material

Contains the following characters:
- Sield (Costume)
- Skeledoodle (Default)
- Skeledoodle (Fire)
- Skeledoodle (Ice)

### CODE REVIEW

**Review by eli-lam — CHANGES_REQUESTED** [review]
Can you add colliders to the skeledoodles

**Review by armandorusso — APPROVED** [review]
Models and animations look amazing! Good job!

**Review by danielwiktorczyk — CHANGES_REQUESTED** [review]
Please rebase first to ensure the Fireball and Magic Shield abilities still work

**Review by danielwiktorczyk — APPROVED** [review]

**Comment by danielwiktorczyk** [comment]
Looks good!

**Review by eli-lam — APPROVED** [review]
Good job!

**Pull request merged**
