### PR TITLE
Add Main Map

### PR DESCRIPTION
**Pull request by armandorusso**
Add Main Map which includes:
- Starting Area
- Frog Campire/Tutorial Scene
- Lost Tree Area
- Intriguing Shack
- Farm House
- Cemetery
- Fisherman Area
- Lake
- Umpkinp Village

Add Assets such as Trees, Buildings (Farm and Shacks), Grass, Rocks, Shovels, Tombstones, Bridge, Campfires, Signs, Ground Textures

Organize each type of objects in different empty objects

### CODE REVIEW

**Review by eli-lam — CHANGES_REQUESTED** [review]
image
- I'm getting stuck at this particular spot
- Make signposts more visible, maybe try to push them out a little more? Closer to the path. 
- Paths should visibly show what they will lead to. If you're trying to keep it a mystery, there should still be hints.
- Create more variety with the terrain levels -> make sharper visual changes in levels/terrain type
- Move BlenderAssets files

**Review by danielwiktorczyk — CHANGES_REQUESTED** [review]
So far, all the Materials, Models, etc, need to be moved from your sandbox to the respective directories in the Assets root. 

Why is the camera skewed 45degrees on teh y? There's no need for this, it isn't isometric anymore

**Comment by danielwiktorczyk** [comment]
Foreground Discussion

image
image
image

**Review by danielwiktorczyk — APPROVED** [review]

**Comment by armandorusso** [comment]
> 
> 
> image
> 
>     * I'm getting stuck at this particular spot
> 
>     * Make signposts more visible, maybe try to push them out a little more? Closer to the path.
> 
>     * Paths should visibly show what they will lead to. If you're trying to keep it a mystery, there should still be hints.
> 
>     * Create more variety with the terrain levels -> make sharper visual changes in levels/terrain type
> 
>     * Move BlenderAssets files

All of your comments have been fixed!
- I fixed the bridge, so you should be able to go over it now
- Added more signposts and rotated & placed them so it can be more visible to the player
- I fixed the terrain and mountains so the player can see whats up ahead more. In conjunction, I added a new camera angle which allows the player to see a lot more further (also they can see the sky a little bit!)
- There is more terrain variety now as well. I did this by lowering the mountains and added small pits which will have water in them later on
- Daniel moved all of the folders and files accordingly in his latest commit

**Comment by armandorusso** [comment]
> 
> 
> So far, all the Materials, Models, etc, need to be moved from your sandbox to the respective directories in the Assets root.
> 
> Why is the camera skewed 45degrees on teh y? There's no need for this, it isn't isometric anymore

Fixed as well!
- I changed the camera angle so the player can see a lot more whats around them. 
- In conjunction, lowered the terrain to fix the camera clipping in all of the areas.

**Review by eli-lam — APPROVED** [review]
Ran through it on call

**Pull request merged**
